# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      # Security checks
      - id: detect-private-key
        files: ''
      - id: detect-aws-credentials
        files: ''

      # File checks
      - id: check-yaml
        files: ^(infrastructure/|backend/|\.github/|\.pre-commit-config\.yaml)
      - id: check-json
        files: ^(infrastructure/|frontend/|backend/)
      - id: check-merge-conflict
      - id: check-added-large-files
        args: ['--maxkb=500']

      # Code quality
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
        args: ['--fix=lf']

  # Python/Django specific
  - repo: https://github.com/pycqa/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        files: ^backend/
        exclude: ^backend/migrations/
        additional_dependencies:
          - flake8-django
        args:
          - '--max-line-length=120'
          - '--extend-ignore=E203'

  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
        files: ^backend/
        exclude: ^backend/migrations/
        args: ['--line-length=120']

  # JavaScript/Frontend specific
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        files: ^frontend/
        types_or: [javascript, jsx, ts, tsx, css, scss, json]
        additional_dependencies:
          - prettier@3.0.3
