services:
  frontend:
    build:
      target: development
    ports:
      - '5173:5173'
    volumes:
      - ./frontend:/app
      - /app/node_modules
    env_file:
      - .env

  backend:
    build:
      target: development
    ports:
      - '8000:8000'
    volumes:
      - ./backend:/app
      - /app/.venv
    env_file:
      - .env
    environment:
      - DJANGO_SETTINGS_MODULE=backend.settings.development

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - '5432:5432'

volumes:
  postgres_data:
